language: node_js
node_js: 8.5
sudo: required
addons:
  ssh_known_hosts: 129.204.164.50
cache:
  directories:
    - node_modules  
before_install:
  - openssl aes-256-cbc -K $encrypted_16d79fa63dc5_key -iv $encrypted_16d79fa63dc5_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm install
after_success:
  - ssh root@$HOST StrictHostKeyChecking=no 'cd ~/V3EX && git pull && npm install && pm2 startOrReload pm2.json'
